config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#login'
  get  '/home',      to: 'static_pages#home'
  get  '/help',      to: 'static_pages#help'
  get  '/about',     to: 'static_pages#about'
  get  '/signup',    to: 'users#new'
  get  '/dashboard', to: 'dashboard#index'
  get  '/login',     to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  post '/medicine',  to: 'medicine#new'
  delete '/logout',  to: 'sessions#destroy'
  
  
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medicine.rb
class Medicine < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :first_name , presence: true
    validates :last_name  , presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def hello
    render html: "hello, world!"
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    
    def index
        @user = User.find_by(email: params[:email].downcase)
    end
end

app/controllers/medicine_controller.rb
class MedicineController < ApplicationController
    
    def index
    end
    
    def new
        @medicine = Medicine.new(:generic => params[:generic_name],
                                 :brand => params[:brand_name],
                                 :price => params[:price],
                                 :Quantity => params[:quantity],
                                 :mg => params[:mg])
        @medicine.save
    end
    
    def create
    end
    
    def update
    end
    
    def edit
    end
    
    def show
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      # redirect_to user
      redirect_to dashboard_url(email: params[:session][:email])
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  
  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # @user = User.new(params[:user])    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: 'User was successfully created.' }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "PharmaC App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/medicine_helper.rb
module MedicineHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
    end
end

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="dashboard.css">
    
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top " id="dashboard-nav">
      <div class="container-fluid">
        <div class="navbar-header">
          <img src="PC.png" class="navbar-brand"/> 
        </div>
        <ul class="nav navbar-nav">
          <li><a href="#">PharmaC</a></li>
        </ul>
        
        <form class="navbar-form navbar-left" id="dashboard-search-bar">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
          </div>
        </form>
        
        <ul class="nav navbar-nav navbar-right" id="dashboard-user">
          <li><a href="#" id="user-data">
            <%= @user.first_name %>
            <%= @user.last_name %>
            <%= gravatar_for @user %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container body">
      <div class="function-buttons">
        <button type="button" class="btn btn-primary">Default</button>
        <button type="button" class="btn btn-success">Default</button>
        <button type="button" class="btn btn-warning">Default</button>
        <a href="#" role="button" class="btn btn-info add" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-plus"></span>Add</a>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <td>Medicine Name</td>
            <td>Stock Amount</td>
            <td>Last Updated</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>john@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>mary@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>july@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>john@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>mary@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>july@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>john@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>mary@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>july@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>john@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>mary@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>july@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>john@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>mary@example.com</td>
          </tr>
          <tr>
            <td>Sample</td>
            <td>10</td>
            <td>july@example.com</td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog" >
      <div class="modal-dialog">
    
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header" style="background-color:#3fbcf0;">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" style="color:white;">Product Information</h4>
          </div>
          <div class="modal-body" style="color:white">
            <div id="modal-form">
              <%= form_tag("/medicine", method: "post") do %>
                <%= label_tag(:generic_name, "Generic Name:") %>
                <%= text_field_tag(:generic_name) %>
                <%= label_tag(:brand_name, "Brand Name:") %>
                <%= text_field_tag(:brand_name) %>
                <%= label_tag(:price, "Price:") %>
                <%= text_field_tag(:price) %>
                <%= label_tag(:quantity, "Quantity:") %>
                <%= text_field_tag(:quantity) %>
                <%= label_tag(:mg, "Milligrams:") %>
                <%= text_field_tag(:mg) %>
            </div>
              <button type="submit" class="btn" id="modal-form-submit">Add To Inventory</button>
            <% end %>  
          </div>
          <div class="modal-footer" style="background-color:#3fbcf0;">
            <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
          </div>
        </div>
    
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title)) %> </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="login.css">
    <link rel="stylesheet" type="text/css" href="signup.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <!--<div>-->
    <!--  <%= debug(params) if Rails.env.development? %>-->
    <!--</div>-->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>

    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

    <h1>Sample App</h1>
    <p>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </p>

app/views/static_pages/login.html.erb
  <div id="login-logo"> 
      <img src="PC.png" />
  </div>
  
  <div class="panel panel-default login-panel">
    
    <div class="panel-body">
      <h3> Login to PharmaC! </h3>
      <div id="login-form">
        <%= form_for(:session, url: login_path) do |f| %>
          <%= f.email_field :email, class: 'form-control login-form', placeholder: 'Email Address'%>
          <%= f.password_field :password, class: 'form-control login-form', placeholder: 'Password' %>
          <%= f.submit "Log in", class: "btn btn-primary login-button" %>
        <% end %>
      </div>
        
    </div>
    
    <div class="panel-footer">
      <h4 id="login-signup">
        Create new account! 
        <%= link_to "Sign Up",  '/signup' %>
      </h4>
    </div>
    
  </div>
  
  <div id="login-footer">
      <%= link_to "Home",   home_path %> 
      <%= link_to "Help",   help_path %> 
      <%= link_to "About",  about_path %>
  </div>
  

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="signup-nav">
  <nav class="navbar">
    <div class="navbar-header">
      <img src="PC.png" />
      <a class="navbar-brand" href="#">PharmaC</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/" class="btn btn-default" role="button">Login</a></li>
    </ul>
  </nav>
</div>

<div class="signup-center">
  <div class="panel panel-default signup-panel">
    <div class="panel-body">
      <div class="row signup-input">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>
          
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
          
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Confirm Password" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <%= f.submit "CREATE MY ACCOUNT", class: "btn btn-primary signup-button" %>
        <% end %>
        <p>Signing up signifies that you have read and agree to the <em>Terms of Service</em> and our <em>Privacy Policy</em>.</p>
      </div>
    </div>
  </div>  
</div>
  

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= gravatar_for @user %>
  <!--<strong>Name:</strong>-->
  <%= @user.first_name %>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>